## first install numpy

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
arr_1D = np.array([1,2,3,4,5])
arr_2D = np.array([[1], [2], [3], [4], [5]])
arr_3D = np.array([[[1]], [[2]], [[3]], [[4]], [[5]]])
print("1D array",arr_1D)
print("2D array",arr_2D)
print("3D array",arr_3D)

1D array [1 2 3 4 5]
2D array [[1]
 [2]
 [3]
 [4]
 [5]]
3D array [[[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]]


## Numpy Array Dimension

In [4]:
arr_0D = np.array(42)
arr_1D = np.array([1, 2, 3, 4, 5])
arr_2D = np.array([[1, 2, 3], [4, 5, 6]])
arr_3D = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr_0D.ndim)
print(arr_1D.ndim)
print(arr_2D.ndim)
print(arr_3D.ndim)

0
1
2
3


In [5]:
dim = np.array([1, 2, 3, 4], ndmin=5)
print(dim)
print('number of dimensions :', dim.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## NumPy Array Indexing

In [6]:
arr = np.array([1, 2, 3, 4])
print(arr[0])
print(arr[2] + arr[3])


1
7


In [7]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print('5th element on 2nd row: ', arr[1, 4])

2nd element on 1st row:  2
5th element on 2nd row:  10


In [8]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [9]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


## NumPy Array Slicing

In [16]:
# 1-D array

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])


[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [19]:
# 2-D array


arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])


[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]
